### ISSUE TITLE
creating partial ellipsoids

### ISSUE THREAD

**Issue by mwarnick123** [poliastro/czml3#101]
Add parameters to the Ellipsoid class in order to create partial ellipsoids

**Comment by Stoops-ML** [comment]
Looking at the [Ellipsoid](https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/Ellipsoid) documenation all properties but distanceDisplayCondition, shadows and subdivisions are implemented in CZML3. I don't see partial ellipsoids on the [sandcastle](https://sandcastle.cesium.com/?src=CZML%20Spheres%20and%20Ellipsoids.html&label=CZML) example.

Closing this issue as it's unclear what properties CZML3 is missing for Ellipsoid. If you can explain in further detail how to create a partial ellipsoid I'll reopen this issue.
