### ISSUE TITLE
PyPi czml3 release is outdated

### ISSUE THREAD

**Issue by mixxen** [poliastro/czml3#105]
Please push a new version to PyPi. We want to obtain new changes in the master branch with pip. I can help with this if you give me access. Thanks.

**Comment by astrojuanlu** [comment]
Thanks for the nudge @mixxen, will do this week 🙏🏽

**Comment by mixxen** [comment]
Let me know if I can help with pushing a new version.

**Comment by Stoops-ML** [comment]
I've made a pull request #108  for this.

**Comment by Stoops-ML** [comment]
PR #108 has been merged. I recommend pushing a new version to pypi and closing this.

**Comment by astrojuanlu** [comment]
Somebody wants to contribute a release workflow using github actions? I'll fill it with my PyPI token of course.

**Comment by Stoops-ML** [comment]
Why not do a manual upload to PyPi?

In any case, are you referring to something like [this](https://github.com/pypa/gh-action-pypi-publish)?

**Comment by astrojuanlu** [comment]
https://github.com/poliastro/czml3/issues/112
