### ISSUE TITLE
czml3 is looking for new maintainers

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/czml3#112]
Full context: https://github.com/poliastro/poliastro/issues/1640

> I don't see the need to archive czml3, we can transition that project.

There's a pending release and a couple of pull requests that need merging. Are there any volunteers to move this project forward?

Please explain your motivation, how you are currently using czml3, and what do you intend to do with it in the future.

**Comment by astrojuanlu** [comment]
cc @Sedictious would you like to step in?

**Comment by Stoops-ML** [comment]
There are some serious problems that require quick fixes for this package to remain usable in my opinion, specifically https://github.com/poliastro/czml3/pull/76, https://github.com/poliastro/czml3/issues/105. Once a maintainer is found I think these problems should be immediately addressed.

If a maintainer can't be found I'd be happy to fill in the position, but I'm probably very much under-qualified for the position. If it's of any relevance, I've written a similar library for Julia called [CZML.jl](https://github.com/Stoops-ML/CZML.jl).

**Comment by ProgramComputer** [comment]
To potential forkers, copy the issues from here using https://github.com/gavinr/github-csv-tools.

**Comment by Sedictious** [comment]
Maintainer sounds a bit "heavy" but I want to try to tackle the open issues (though I expect a non-insignificant ramp up time). To clarify, all PRs would need to be opened to the open project correct (if so I could help with creating the fork, cloning the issues and redirecting to the new repo). I understand that this repo will be archived in any case correct?

**Comment by astrojuanlu** [comment]
I don't intend to archive the repo if anyone wants to step in as maintainer (this is different from what I did in poliastro)

**Comment by fbl100** [comment]
Are you still looking for a maintainer?  I have used czml3 across multiple projects/companies and have a vested interest in keeping it alive and well.  Can you briefly explain what is involved in being a maintainer?

**Comment by astrojuanlu** [comment]
Hi @fbl100 ! With "maintainer" I mean someone who cares about the library, fixes some of the open issues, and as a result of the trust earned by the community earns write access to the repository.

There are a few bugs and gaps so feel free to start contributing, I don't have a lot of time to review big PRs but I'll do my best.

May I ask what have you used czml3 for? 😊

**Comment by fbl100** [comment]
Broadly speaking, I've used it to visualize satellite scheduling results, so showing orbits, models, beams, ground tracks, etc.

I have a small batch of updated models that I use for cases where the official library doesn't have support (see: PolylineArrow).  It's on my list to gather my changes and submit them as a PR.

Not sure if that answers your question, but I'd be interested in becoming a maintainer at some point.

**Comment by astrojuanlu** [comment]
@Stoops-ML has been making some good contributions lately so I added him to the organization with Triage permissions for now 💪🏼

**Comment by fbl100** [comment]
That' great.  I've been working on getting my local mods into a PR.  Hoping to have it ready for review in the next week or so.

**Comment by astrojuanlu** [comment]
Just a heads up, @Stoops-ML continued to make consistently good contributions over the past month so now he has write access. The CI is in a much better state now so we're close to tagging a release.

**Comment by Stoops-ML** [comment]
@astrojuanlu are there any other additions you'd like before a version bump? I've finished all the work that I had planned to do before a version bump.

Also, I remember that you had said somewhere that you wanted to bump to v1.0.0 once all the packets have been added to the library. That still true (i.e. next bump is v0.8.0)?

**Comment by astrojuanlu** [comment]
> are there any other additions you'd like before a version bump? 

not really, let's proceed!

**Comment by astrojuanlu** [comment]
We made a release 🎉 

Now what would be _awesome_ to close this ticket would be to have another person review @Stoops-ML PRs that's not just me. Everybody in this thread is welcome to get more involved in that regard, even if you don't have time to author PRs yourself.

**Comment by fbl100** [comment]
Just when I thought I was going to have time to be a maintainer, I got slammed at work.  I can definitely review PR's, and I'll try to find the time (after the release?) to check the current packet definitions against some of the ones that I've made locally over the years.

**Comment by Stoops-ML** [comment]
I’d like to pitch myself again. I’ve basically rewritten/modified the majority of the codebase in v2 and have time to maintain the package. There’s bug fixes I have ready to merge, but I’ve been waiting on #162 for a few days now.

**Comment by astrojuanlu** [comment]
@Stoops-ML is effectively maintaining the package now. The only thing missing is that we need a co-maintainer, hence somebody that will review PRs so that at least 1 more person will look at the code before going in. When we find them, I'm happy to grant them triage rights, maintainership rights to @Stoops-ML, and close this issue.

**Comment by astrojuanlu** [comment]
Been thinking about this for a few days. I think it's unreasonable to expect others to step in and start reviewing code.

There's a big PR incoming https://github.com/poliastro/czml3/pull/163 and I don't think I'll ever find the motivation to review it. This is on top of a major refactor that was merged recently https://github.com/poliastro/czml3/pull/154

A year ago I said that we could transition czml3 but now the truth is that I'd like to archive `poliastro/czml3`.

At the same time, unlike `poliastro/poliastro`, I'm not picky about squatting this name for myself forever.

I offer this path forward:

1. We change the trusted publisher of https://pypi.org/project/czml3/ to be https://github.com/Stoops-ML/czml3
2. We make @Stoops-ML co-owner of https://pypi.org/project/czml3/
3. I archive this repository
4. I step down as owner of `czml3`

This is equivalent to giving @Stoops-ML "the keys" for `czml3` on PyPI.

If there are no major disagreements, and crucially @Stoops-ML is okay, let's proceed.

**Comment by Stoops-ML** [comment]
Thanks very much for having faith in me! I’d love to take over the reins and continue developing this package. 

On my end I’ll try to find someone / some people that can help with code reviews. 

The main things I’ll be focusing on are bug fixes, expanding property validation and perhaps incorporating some Cesium Ion properties (but I don’t currently have a licence for them). So no big changes should be expected in the coming months.

**Comment by astrojuanlu** [comment]
I've done (1) and (2) already, @Stoops-ML please confirm

**Comment by Stoops-ML** [comment]
Confirming that I am now co-owner

**Comment by astrojuanlu** [comment]
About to do (3), and will do (4) right after. _Ad astra!_
