### ISSUE TITLE
Remove Cesium ion runtime dependency in CZMLWidget

### ISSUE THREAD

**Issue by kerel-fs** [poliastro/czml3#55]
Currently CZMLWidget uses the default Cesium Ion token. With every release of Cesium the old token will be invalidated, breaking old notebooks ~~[citation needed]~~(see https://github.com/AnalyticalGraphicsInc/cesium/issues/8433#issuecomment-561257678). Afaik this token is only required to be able to access the imagery for the basemap via Cesium Ion.

[Example notebook](https://gist.github.com/kerel-fs/6cdcfe33b933329f807382b0c5bbf1a9) [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gist/kerel-fs/6cdcfe33b933329f807382b0c5bbf1a9/master)
screenshot:
![Screenshot_2019-12-12 poliastro_issue817 - Jupyter Notebook](https://user-images.githubusercontent.com/10089607/70746986-3ea2ad00-1d27-11ea-9459-8de081c96ce6.png)

**possibles fixes**
- option A: find a new, "long-term" reliable source for hosting the basemaps
- option B: provide a static basemap
- something else?

**Related issues**
- discussion of various open-data basemap resources in poliastro/cesium-app#4

**Comment by astrojuanlu** [comment]
Related to #49. I think we can change the default basemap and that's it (and whoever happens to have a Cesium Ion token can always use the best basemap they can)
