### ISSUE TITLE
PyPi release cycle

### ISSUE THREAD

**Issue by idanmiara** [poliastro/czml3#75]
I see that the last release, 0.5.3,  was about 10 months ago.
Since then there were many additions and fixes to `Master`.
Would you please release a new version into `PyPi` occasionally?
Thanks!

**Comment by astrojuanlu** [comment]
You're totally right @idanmiara , this has been delayed for too long! I am in the process of making a release right now, and hopefully I will be more responsive going forward. Will close this issue when done.

**Comment by idanmiara** [comment]
Thanks!

**Comment by astrojuanlu** [comment]
czml3 0.5.4 is available 🎉
