### ISSUE TITLE
Lack of support for positional references

### ISSUE THREAD

**Issue by jpromers** [poliastro/czml3#93]
Support is necessary for positional references...

`
polyline":{
       ...
      "arcType":"NONE",
      "positions":{
        "references":[
          "Facility/AGI#position","Satellite/ISS#position"
        ]
      }

`
Position constructor doesn't accept "references" attribute.  This comes from the CZML simple example from the sandcastle that is the basis for your "simple" example.

**Comment by astrojuanlu** [comment]
Hi @jpromers , sorry for the delay. `PositionList` accepts `references`:

https://github.com/poliastro/czml3/blob/cea9aab56e3dd4dbe3874f4d16928dcf32d7093f/src/czml3/properties.py#L431

and `Position` accepts `reference`:

https://github.com/poliastro/czml3/blob/cea9aab56e3dd4dbe3874f4d16928dcf32d7093f/src/czml3/properties.py#L230

I think you might be confusing the two. It's not your fault, CZML documentation is quite lacking. Please let me know if we can close this issue.
