### ISSUE TITLE
Position missing arguments for interval

### ISSUE THREAD

**Issue by mwarnick123** [poliastro/czml3#94]

**Comment by mwarnick123** [comment]
Found in the the tests how to use the epoch in Position

**Comment by astrojuanlu** [comment]
Hi @mwarnick123 , can you give some more details? I don't see `interval` here: https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/Position

**Comment by astrojuanlu** [comment]
This: https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/CZML-Structure#intervals

**Comment by astrojuanlu** [comment]
Isn't this solved by

```
Packet(position=IntervalValue(...))
```

?

**Comment by mwarnick123** [comment]
Hi @astrojuanlu, I want a polygon to appear for only a certain period of time and to write that I need to write the following for the position:
```
position: {
      interval: "2012-08-04T16:00:00Z/2012-08-04T17:00:00Z",
      cartographicDegrees: [-45.0, 20, 4000000],
    },
```

to get the interval I can use TimeInterval(), but I still need to declare interval which can be done in the Position() class.

This can be used on other objects and placed in the PositionList() class as well.

**Comment by mwarnick123** [comment]
https://sandcastle.cesium.com/?src=CZML%20Polygon%20-%20Interpolating%20References.html&label=CZML This is the example I am trying to use czml3 to create the czml file
