### ISSUE TITLE
missing polygon arguments and missing polyline arguments

### ISSUE THREAD

**Issue by mwarnick123** [poliastro/czml3#96]
There is no available arguments for polygon holes and polyline characteristics

**Comment by Stoops-ML** [comment]
Polygon holes have now been added.

It's unclear to me what you mean by Polyline characteristics (see [here](https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/Polyline) for it's properties).

I'm closing this issue. If there are specific Polyline properties that are missing from the documentation please open another issue.
