### ISSUE TITLE
cesium token

### ISSUE THREAD

**Issue by giswqs** [poliastro/czml3#98]
I am trying to use my own cesium token. However, it does not seem to work. I am new to Cesium. Any advice? Thanks. 

![image](https://user-images.githubusercontent.com/5016453/145929148-8ff1b5aa-2a79-4dfe-b11a-ace918f73e95.png)

**Comment by astrojuanlu** [comment]
Hi @giswqs ! I have often observed that, once you try the widget with a given token (or the default one), it gets "stuck" and you need to restart the notebook, clear the outputs, refresh the browser window, and execute the cells again to make it work. Could you please try that? If it still doesn't work I'll have a closer look.

**Comment by giswqs** [comment]
It seems the issue has been fixed by #99. Thanks. 

![image](https://user-images.githubusercontent.com/5016453/146037156-b9be8dcb-5a23-4aa2-aa76-be745b5cbab2.png)
